version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "printjson(db.serverStatus())"]
      interval: 10s
      timeout: 5s
      retries: 3

  savingstracker:
    build:
      context: .
    image: ahdjr/savingstracker:v1.0
    container_name: savingstracker_container
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/venv
    depends_on:
      - mongodb
    env_file: .env

volumes:
  mongodb-data: